<?php
/**
 * @author Endora
 * @copyright Copyright (c) Endora (https://endora.software)
 * @package ExpertSender_Ecdp
 */

/** @var \ExpertSender\Ecdp\Block\TrackingScript $block */
?>
<?php if ($block->getIsTrackingEnabled()): ?>
    <?php $trackingScript = $block->getTrackingScript(); ?>
    <?php if ($trackingScript): ?>
        <?= /* @noEscape */ $trackingScript; ?>
    <?php endif; ?>
<?php endif; ?>
